---
- hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - community.digitalocean
  
  tasks:
    - name: Ensure a droplet is present with SSH keys installed
      digital_ocean_droplet:
        state: present
        id: 123
        name: mydroplet
        oauth_token: XXX
        size: 2gb
        region: sfo1
        ssh_keys: ['1534404', '1784768']
        image: ubuntu-16-04-x64
        wait_timeout: 500
